backend:
  # name: test-repo
  name: git-gateway
  branch: master

media_folder: "public/images/upload"
public_folder: "/images/upload"
publish_mode: editorial_workflow

collections:
  - name: "home"
    label: "ホーム"
    delete: false
    editor:
      preview: false
    files:
      - name: "home"
        label: "Home"
        file: "content/home.md"
        fields:
          - label: "サイトの名前"
            name: "site_name"
            widget: "string"
            hint: "Ex. Netlify CMS テスト"
          - label: "サイトの説明"
            name: "site_description"
            widget: "string"
            hint: "Ex. このサイトはNetlify CMS テスト用に作成しました"
  - name: "blog-articles"
    label: "ブログ"
    create: true
    delete: true
    editor:
      preview: false
    slug: "{{id}}"
    identifier_field: id
    folder: "content/blog"
    fields:
      - label: "URLに含まれるID"
        name: "id"
        wiget: string
        pattern:
          - "[a-z0-9][a-z0-9\\-]+[a-z0-9]"
          - "数値とアルファベットのIDを指定してください"
        hint: "Ex. sample-page"
      - label: "日付"
        name: "date"
        widget: date
        format: "YYYY-MM-DD"
      - label: "タイトル"
        name: "title"
        widget: string
      - label: "説明"
        name: "description"
        widget: string
      - label: "サムネイル画像"
        name: "image"
        widget: image
      - label: 本文
        name: body
        widget: markdown
