backend:
  name: git-gateway
  branch: master

media_folder: public/img
public_folder: img
publish_mode: editorial_workflow

collections:
  - name: "home"
    label: "ホーム"
    delete: false
    editor:
      preview: false
    files:
      - name: "home"
        label: "Home"
        file: "content/home.md"
        fields:
          - label: "サイトの名前"
            name: "site_name"
            widget: "string"
            hint: "Ex. Netlify CMS テスト"
          - label: "サイトの説明"
            name: "site_description"
            widget: "string"
            hint: "Ex. このサイトはNetlify CMS テスト用に作成しました"
